name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/vga_system_api.sln
    - name: Build
      run: dotnet build --no-restore ./src/vga_system_api.sln

  deploy-backend:
    runs-on: self-hosted

    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy with Docker Compose
        run: docker compose -f docker-compose.yml up --build -d
        